version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: vector-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vectordemo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  backend:
    build: ./backend
    container_name: vector-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432/vectordemo
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: vector-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

volumes:
  pgdata:
